{% set name = "mo-logs" %}
{% set version = "7.252.22317" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-logs-{{ version }}.tar.gz
  sha256: e79ed58c67347414c8cc0d435a28c3e968f6130566d6b821cd894cad0dff23f8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7
    - mo-dots ==9.251.22317
    - mo-future ==6.230.22310
    - mo-imports ==7.251.22317
    - mo-kwargs ==7.252.22317

test:
  imports:
    - mo_logs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/klahnakoski/mo-logs
  summary: More Logs! Structured Logging and Exception Handling
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
