{% set name = "mo-logs" %}
{% set version = "7.330.23004" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-logs-{{ version }}.tar.gz
  sha256: 1d47b3efa905b25828054f54cc355cd2caa3b22d4065a2b55fa7bf3729c39a7b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7
    - mo-dots ==9.300.22349
    - mo-future ==7.298.22349
    - mo-imports ==7.298.22349
    - mo-kwargs ==7.310.22362

test:
  imports:
    - mo_logs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/klahnakoski/mo-logs
  summary: More Logs! Structured Logging and Exception Handling
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
