{% set name = "mo-logs" %}
{% set version = "7.4.21313" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mo-logs-{{ version }}.tar.gz
  sha256: 7ca3c563dc0bb859ea131330ec5c4a6ae0c089f383464164bef944dfa7285e92

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7
    - mo-dots 5.22.21182
    - mo-future 5.17.21182
    - mo-imports 5.17.21182
    - mo-kwargs 5.23.21182

test:
  imports:
    - mo_logs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/klahnakoski/mo-logs
  summary: More Logs! Structured Logging and Exception Handling
  license: MPL-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
